In [3]:
import numpy as np

In [7]:
data = np.genfromtxt('data/ml-1m/ratings.dat',delimiter='::',dtype=np.int64)
data[:10]

array([[        1,      1193,         5, 978300760],
       [        1,       661,         3, 978302109],
       [        1,       914,         3, 978301968],
       [        1,      3408,         4, 978300275],
       [        1,      2355,         5, 978824291],
       [        1,      1197,         3, 978302268],
       [        1,      1287,         5, 978302039],
       [        1,      2804,         5, 978300719],
       [        1,       594,         4, 978302268],
       [        1,       919,         4, 978301368]], dtype=int64)

In [11]:
print(data.shape)

(1000209, 4)


In [16]:
movie_ids=np.unique(data[:,1])
print(movie_ids[:5])
print(movie_ids.shape)

[1 2 3 4 5]
(3706,)


In [21]:
mean_values=[]
for movie_id in movie_ids:
    data_for_movie=data[data[:,1]==movie_id,:]
    value=data_for_movie[:,2].mean()
    mean_values.append([movie_id,value])

In [22]:
mean_values[:10]

[[1, 4.146846413095811],
 [2, 3.20114122681883],
 [3, 3.01673640167364],
 [4, 2.7294117647058824],
 [5, 3.0067567567567566],
 [6, 3.8787234042553194],
 [7, 3.410480349344978],
 [8, 3.014705882352941],
 [9, 2.656862745098039],
 [10, 3.5405405405405403]]

In [23]:
mean_arry=np.array(mean_values,dtype=np.float32)
print(mean_arry[:10])
print(mean_arry.shape)

[[ 1.         4.1468463]
 [ 2.         3.201141 ]
 [ 3.         3.0167365]
 [ 4.         2.7294118]
 [ 5.         3.0067568]
 [ 6.         3.8787234]
 [ 7.         3.4104803]
 [ 8.         3.014706 ]
 [ 9.         2.6568627]
 [10.         3.5405405]]
(3706, 2)


In [20]:
np.savetxt('data/movieId_result.csv',mean_arry,delimiter=',')