In [3]:
import numpy as np 

a=[1,2,3,4,5,'s']
b=np.array(a)
print(a)
print(b)

[1, 2, 3, 4, 5, 's']
['1' '2' '3' '4' '5' 's']


! pip install numpy

In [7]:
b1=np.arange(10)
print(b1)

[0 1 2 3 4 5 6 7 8 9]


In [8]:
a=[[1,2,3],[4,5,6]]
b=np.array(a)
print(b)


[[1 2 3]
 [4 5 6]]


In [10]:
a=[1,2,3,4,5,6]
b=np.array(a).reshape(2,3)
c=np.array(a).reshape(3,2)
print(b)
print(b.shape)
print(c.shape)


[[1 2 3]
 [4 5 6]]
(2, 3)
(3, 2)


In [14]:
print(b[0][1])
print(b[0,1])

2
2


In [16]:
a=[[1,2,3,],[4,5,6],[7,8,9]]
b=np.array(a)
print(a)
print(b)

[[1, 2, 3], [4, 5, 6], [7, 8, 9]]
[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [26]:
print(a[:][1])
print("---")
print(b[:,[0,2]])
print("----")
print(b[::-1,[0,2]])
print("---")
print(b[1::-1])

[4, 5, 6]
---
[[1 3]
 [4 6]
 [7 9]]
----
[[7 9]
 [4 6]
 [1 3]]
---
[[4 5 6]
 [1 2 3]]


In [36]:
list1=[1,2,3]
list2=[4,5,6]
print(list1+list2)
print(list1*3)
arr1=np.arange(1,10).reshape(3,3)
arr2=np.arange(11,20).reshape(3,3)
print(arr1+arr2)
print(arr1*arr2)
print(arr2-arr1)
print(arr1*arr2)
print(arr1*2)
print(arr2/arr1)
print(arr2//arr1)

[1, 2, 3, 4, 5, 6]
[1, 2, 3, 1, 2, 3, 1, 2, 3]
[[12 14 16]
 [18 20 22]
 [24 26 28]]
[[ 11  24  39]
 [ 56  75  96]
 [119 144 171]]
[[10 10 10]
 [10 10 10]
 [10 10 10]]
[[ 11  24  39]
 [ 56  75  96]
 [119 144 171]]
[[ 2  4  6]
 [ 8 10 12]
 [14 16 18]]
[[11.          6.          4.33333333]
 [ 3.5         3.          2.66666667]
 [ 2.42857143  2.25        2.11111111]]
[[11  6  4]
 [ 3  3  2]
 [ 2  2  2]]


In [39]:
arr3=np.array([10,20,30])
print(arr1*arr3)


[[ 10  40  90]
 [ 40 100 180]
 [ 70 160 270]]


In [42]:
print(arr1)
print(arr1.sum())
print(np.sum(arr1))
print(arr1.sum(axis=0))
print(np.sum(arr1,axis=1))
print(arr1.mean(axis=0))

[[1 2 3]
 [4 5 6]
 [7 8 9]]
45
45
[12 15 18]
[ 6 15 24]
[4. 5. 6.]


In [44]:
a=[5,3,2,4,1,7,6,9,8]
arr=np.array(a).reshape(3,3)
arr

array([[5, 3, 2],
       [4, 1, 7],
       [6, 9, 8]])

In [47]:
print(np.sort(arr))
print(np.sort(arr, axis=0))
print(np.sort(arr, axis=1))
print("---")
print(np.sort(arr, axis=0)[::-1,::]) #열기준 행순서 역순
print("---")
print(np.sort(arr, axis=1)[::, ::-1]) #행기준 열순서 역순


[[2 3 5]
 [1 4 7]
 [6 8 9]]
[[4 1 2]
 [5 3 7]
 [6 9 8]]
[[2 3 5]
 [1 4 7]
 [6 8 9]]
---
[[6 9 8]
 [5 3 7]
 [4 1 2]]
---
[[5 3 2]
 [7 4 1]
 [9 8 6]]


In [50]:
print(arr)
print('---')
print(arr.transpose()) #전치행렬

[[5 3 2]
 [4 1 7]
 [6 9 8]]
---
[[5 4 6]
 [3 1 9]
 [2 7 8]]


In [51]:
print(arr>=5)
print(np.all(arr>3))
print(np.any(arr>3))

[[ True False False]
 [False False  True]
 [ True  True  True]]


요소 값 검사

In [54]:
a1=np.zeros([3,3])
b1=np.ones([4,5])
print(a1)
print(b1)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]


In [56]:
arr.shape
b1=np.ones_like(arr)
b2=np.zeros_like(arr)
print(b1)
print(b2)

[[1 1 1]
 [1 1 1]
 [1 1 1]]
[[0 0 0]
 [0 0 0]
 [0 0 0]]
